Add advping and bossping
AriusX7/gobcog pull request #4
Opened 2020-12-07 07:38 UTC by AriusX7

At the moment, the role ping commands simply ping the role without any other message. If you have suggestions for messages, please leave them here or on Discord.

2020-12-07 11:00 UTC, fourjr requested changes
Just some quick things I noticed. Haven't looked in depth/tested yet.

Would we want a system where it toggles? instead of an add/remove command?

2020-12-07 11:00 UTC, fourjr commented on adventure/role.py
> +                await ctx.author.add_roles(*[role])
```suggestion
                await ctx.author.add_roles(role)
```

2020-12-07 11:00 UTC, fourjr commented on adventure/role.py
> +    async def _roleset_general(self, ctx: Context, *, role: Optional[discord.Role]):
```suggestion
    async def _roleset_general(self, ctx: Context, *, role: discord.Role=None):
```
It's not necessary to put optional & none is clearer.

2020-12-07 11:00 UTC, fourjr commented on adventure/role.py
> +    async def _roleset_boss(self, ctx: Context, *, role: Optional[discord.Role] = None):
```suggestion
    async def _roleset_boss(self, ctx: Context, *, role: discord.Role = None):
```
Not necessary to use both optional/none (similar to above)

2020-12-07 11:00 UTC, fourjr commented on adventure/role.py
> +                _("Set {role} as all adventures role.".format(role=role.mention)),
```suggestion
                _("Set {role} as all adventures role.").format(role=role.mention),
```
Wrong bracket placement with the translator

2020-12-07 16:56 UTC, fourjr requested changes
These are the rest of my comments, looks good. Don't think I will ever have the time to test this extensively until late this week. Feel free to push after you test.

2020-12-07 16:56 UTC, fourjr commented on adventure/role.py
> +    async def bossrole(self, ctx: Context, *, duration: Optional[str]):
```suggestion
    async def bossrole(self, ctx: Context, *, duration=None)
```
same as above

2020-12-07 16:56 UTC, fourjr commented on adventure/role.py
> +    async def advrole(self, ctx: Context, *, duration: Optional[str]):
```suggestion
    async def advrole(self, ctx: Context, *, duration=None):
```

2020-12-07 18:20 UTC, AriusX7 commented
> Would we want a system where it toggles? instead of an add/remove command?

Not too sure about this. Users will have to use two commands if they want to change temporary role to permanent role if we change the behaviour to toggle (first command invocation will remove the "temp" role, second will add the role as permanent).

Personally I prefer having separate commands, but I'd be fine with having toggle behaviour.

2020-12-10 07:46 UTC, fourjr approved these changes

2020-12-10 09:02 UTC, merged